declare module "shutterbug";
declare module "heapify";
declare module "timeseries-analysis";
declare module "*.glsl";
declare module "*.less";
declare module "*.css";
declare module "*.png";
declare module "*.jpg";
declare module "*.svg";
