import {RockKeyLabelArray} from "./types";

export const rockKeyLabels: RockKeyLabelArray = [
  "Gabbro",
  "Basalt",
  "Diorite",
  "Andesite",
  "Granite",
  "Rhyolite",
  "Mantle (brittle)",
  "Mantle (ductile)",
  "Low Grade Metamorphic Rock (Subduction Zone)",
  "Medium Grade Metamorphic Rock (Subduction Zone)",
  "High Grade Metamorphic Rock (Subduction Zone)",
  "Low Grade Metamorphic Rock (Continental Collision)",
  "Medium Grade Metamorphic Rock (Continental Collision)",
  "High Grade Metamorphic Rock (Continental Collision)",
  "Contact Metamorphism",
  "Sandstone",
  "Shale",
  "Limestone",
  "Oceanic Sediments",
  "Continental Sediments",
  "Iron-poor Magma",
  "Intermediate Magma",
  "Iron-rich Magma",
  "Sky",
  "Ocean",
];
