name: Release New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag to release
        required: true

env:
  BUCKET: models-resources
  PREFIX: ${{ github.event.repository.name }}
  SRC_FILE: index-top.html
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: >-
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ env.SRC_FILE }}
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
